package top.baixiaosheng.mygraduationserver.dataobject;

public class AvatarDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.id
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.uid
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.path
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_avatar.avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    private byte[] avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.id
     *
     * @return the value of user_avatar.id
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.id
     *
     * @param id the value for user_avatar.id
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.uid
     *
     * @return the value of user_avatar.uid
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.uid
     *
     * @param uid the value for user_avatar.uid
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.path
     *
     * @return the value of user_avatar.path
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.path
     *
     * @param path the value for user_avatar.path
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_avatar.avatar
     *
     * @return the value of user_avatar.avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public byte[] getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_avatar.avatar
     *
     * @param avatar the value for user_avatar.avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
}