package top.baixiaosheng.mygraduationserver.dataobject;

import java.util.Arrays;

public class MedicalRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_medical_record.id
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_medical_record.uid
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_medical_record.medical_record_path
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    private String medicalRecordPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_medical_record.medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    private byte[] medicalRecord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_medical_record.id
     *
     * @return the value of user_medical_record.id
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_medical_record.id
     *
     * @param id the value for user_medical_record.id
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_medical_record.uid
     *
     * @return the value of user_medical_record.uid
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_medical_record.uid
     *
     * @param uid the value for user_medical_record.uid
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_medical_record.medical_record_path
     *
     * @return the value of user_medical_record.medical_record_path
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public String getMedicalRecordPath() {
        return medicalRecordPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_medical_record.medical_record_path
     *
     * @param medicalRecordPath the value for user_medical_record.medical_record_path
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public void setMedicalRecordPath(String medicalRecordPath) {
        this.medicalRecordPath = medicalRecordPath == null ? null : medicalRecordPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_medical_record.medical_record
     *
     * @return the value of user_medical_record.medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public byte[] getMedicalRecord() {
        return medicalRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_medical_record.medical_record
     *
     * @param medicalRecord the value for user_medical_record.medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    public void setMedicalRecord(byte[] medicalRecord) {
        this.medicalRecord = medicalRecord;
    }

}