package top.baixiaosheng.mygraduationserver.dao;

import top.baixiaosheng.mygraduationserver.dataobject.AvatarDO;

public interface AvatarDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int insert(AvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int insertSelective(AvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    AvatarDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int updateByPrimaryKeySelective(AvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(AvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Tue Apr 20 00:47:22 CST 2021
     */
    int updateByPrimaryKey(AvatarDO record);


    //通过用户id查找
    AvatarDO selectByUId(Integer uid);
    //通过用户id更新
    int updateByUIdSelective(AvatarDO record);
}