package top.baixiaosheng.mygraduationserver.dao;

import top.baixiaosheng.mygraduationserver.dataobject.MedicalRecordDO;
import top.baixiaosheng.mygraduationserver.service.model.MedicalRecordQueryVo;

public interface MedicalRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int insert(MedicalRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int insertSelective(MedicalRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    MedicalRecordDO selectByPrimaryKey(Integer id);
    //MedicalRecordDO[] selectByUid(Integer uid);
    MedicalRecordDO[] selectByUid(Integer uid);
    MedicalRecordDO selectByUidAndPath(MedicalRecordQueryVo medicalRecordQueryVo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int updateByPrimaryKeySelective(MedicalRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(MedicalRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_medical_record
     *
     * @mbg.generated Wed Apr 28 20:46:30 CST 2021
     */
    int updateByPrimaryKey(MedicalRecordDO record);
    int updateByUIdSelective(MedicalRecordQueryVo medicalRecordQueryVo);
}